# Generated by Django 5.1.14 on 2026-08-06 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='告警ID')),
                ('alert_type', models.CharField(choices=[('fire', '火情'), ('smoke', '烟雾'), ('high_temp', '高温'), ('device_fault', '设备故障'), ('low_battery', '低电量'), ('offline', '设备离线'), ('env_threshold', '环境参数超阈值')], max_length=32, verbose_name='告警类型')),
                ('alert_level', models.CharField(choices=[('level_3', '三级(提示)'), ('level_2', '二级(预警)'), ('level_1', '一级(紧急)')], max_length=32, verbose_name='告警级别')),
                ('status', models.CharField(choices=[('new', '新告警'), ('acknowledged', '已确认'), ('dispatched', '已派单'), ('processing', '处理中'), ('resolved', '已处置'), ('false_alarm', '误报'), ('escalated', '已升级')], default='new', max_length=32, verbose_name='告警状态')),
                ('title', models.CharField(max_length=256, verbose_name='告警标题')),
                ('description', models.TextField(blank=True, verbose_name='告警描述')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='所属区域')),
                ('forest_zone', models.CharField(blank=True, max_length=128, verbose_name='林区')),
                ('ai_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='AI置信度')),
                ('ai_category', models.CharField(blank=True, max_length=64, verbose_name='AI识别类别')),
                ('screenshot_url', models.URLField(blank=True, verbose_name='截图URL')),
                ('thermal_image_url', models.URLField(blank=True, verbose_name='热成像URL')),
                ('assigned_to', models.CharField(blank=True, max_length=128, verbose_name='指派给')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='指派时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处置说明')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'db_table': 'alerts',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64, verbose_name='操作类型')),
                ('operator', models.CharField(max_length=128, verbose_name='操作人')),
                ('content', models.TextField(blank=True, verbose_name='操作内容')),
                ('photo_urls', models.JSONField(default=list, verbose_name='现场照片')),
                ('video_url', models.URLField(blank=True, verbose_name='现场视频')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='现场位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='alerts.alert')),
            ],
            options={
                'verbose_name': '告警处置记录',
                'verbose_name_plural': '告警处置记录',
                'db_table': 'alert_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FireTracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='起火点经度')),
                ('origin_latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='起火点纬度')),
                ('origin_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='定位置信度')),
                ('algorithm', models.CharField(default='FARSITE', max_length=64, verbose_name='算法')),
                ('input_devices', models.JSONField(default=list, verbose_name='输入设备列表')),
                ('weather_data', models.JSONField(default=dict, verbose_name='气象数据')),
                ('spread_prediction_1h', models.JSONField(default=dict, verbose_name='1小时预测')),
                ('spread_prediction_3h', models.JSONField(default=dict, verbose_name='3小时预测')),
                ('spread_prediction_6h', models.JSONField(default=dict, verbose_name='6小时预测')),
                ('control_strategy', models.JSONField(default=dict, verbose_name='防控策略')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fire_tracing', to='alerts.alert')),
            ],
            options={
                'verbose_name': '火情溯源',
                'verbose_name_plural': '火情溯源',
                'db_table': 'fire_tracing',
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_level', 'status'], name='alerts_alert_l_3c661c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', '-occurred_at'], name='alerts_alert_t_dcd778_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['region', '-occurred_at'], name='alerts_region_288adc_idx'),
        ),
    ]
