# Generated by Django 5.1.14 on 2026-08-07 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('alert_type', models.CharField(choices=[('fire', '火情'), ('smoke', '烟雾'), ('high_temp', '高温'), ('device_fault', '设备故障'), ('low_battery', '低电量'), ('offline', '设备离线'), ('env_threshold', '环境参数超阈值')], max_length=32, verbose_name='适用告警类型')),
                ('alert_level', models.CharField(choices=[('level_3', '三级(提示)'), ('level_2', '二级(预警)'), ('level_1', '一级(紧急)')], max_length=32, verbose_name='告警级别')),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='0~1，低于阈值不触发', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='AI置信度阈值')),
                ('temperature_threshold', models.FloatField(blank=True, null=True, verbose_name='温度阈值(℃)')),
                ('humidity_threshold', models.FloatField(blank=True, null=True, verbose_name='湿度阈值(%RH)')),
                ('push_channels', models.JSONField(default=list, verbose_name='推送方式')),
                ('response_seconds', models.PositiveIntegerField(default=300, verbose_name='响应时限(秒)')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='适用区域')),
                ('description', models.TextField(blank=True, verbose_name='规则说明')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'alert_rules',
                'ordering': ['alert_level', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertReinforcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=128, verbose_name='申请人')),
                ('reason', models.TextField(verbose_name='增援事由')),
                ('contact', models.CharField(blank=True, max_length=64, verbose_name='联系方式')),
                ('required_people', models.PositiveIntegerField(default=1, verbose_name='需求人数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已受理'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=32, verbose_name='状态')),
                ('handler_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinforcements', to='alerts.alert')),
            ],
            options={
                'verbose_name': '告警增援',
                'verbose_name_plural': '告警增援',
                'db_table': 'alert_reinforcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
