# Generated by Django 5.1.14 on 2026-08-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_rules_reinforcements'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='apply_scope',
            field=models.CharField(choices=[('global', '全部设备'), ('region', '按林区'), ('device_type', '按设备类型'), ('devices', '指定设备')], db_index=True, default='global', max_length=32, verbose_name='作用范围'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='device_type',
            field=models.CharField(blank=True, choices=[('dual_camera', '双目智能监测云台'), ('env_sensor', '多参数环境传感器'), ('ai_gateway', 'AI边缘网关'), ('drone', '无人机')], max_length=32, verbose_name='适用设备类型'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='alert_rules', to='devices.device', verbose_name='指定设备'),
        ),
    ]
