# Generated by Django 5.1.14 on 2026-08-10 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_rule_apply_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='工单号')),
                ('title', models.CharField(max_length=256, verbose_name='工单标题')),
                ('description', models.TextField(blank=True, verbose_name='工单说明')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('normal', '普通'), ('low', '低')], default='normal', max_length=16, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待接单'), ('accepted', '已接单'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=32, verbose_name='工单状态')),
                ('assignee_name', models.CharField(blank=True, max_length=128, verbose_name='处理人姓名')),
                ('creator_name', models.CharField(blank=True, max_length=128, verbose_name='创建人姓名')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='所属区域')),
                ('forest_zone', models.CharField(blank=True, max_length=128, verbose_name='林区')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接单时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('result_note', models.TextField(blank=True, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='alerts.alert', verbose_name='关联告警')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'work_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='work_orders_status_48be91_idx'), models.Index(fields=['assignee', 'status'], name='work_orders_assigne_f50155_idx')],
            },
        ),
    ]
