# Generated by Django 5.1.14 on 2026-08-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_work_orders'),
        ('devices', '0003_org_tenant_scope'),
        ('users', '0004_org_tenant_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='users.organization', verbose_name='所属组织'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to='users.organization', verbose_name='所属组织'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='users.organization', verbose_name='所属组织'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', '-occurred_at'], name='alerts_organiz_c2acf2_idx'),
        ),
    ]
