# Generated by Django 5.1.14 on 2026-08-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_org_tenant_scope'),
        ('users', '0006_forest_zone_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='forest_zone_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='users.forestzone', verbose_name='所属林区'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='forest_zone_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='users.forestzone', verbose_name='适用林区'),
        ),
    ]
