# Generated by Django 5.1.14 on 2026-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0008_backfill_alert_organization"),
        ("devices", "0004_forest_zone_master"),
        ("users", "0010_system_settings_org_scope"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["organization", "status", "-occurred_at"],
                name="alerts_organiz_661d00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "-occurred_at"], name="alerts_status_559570_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["forest_zone", "-occurred_at"], name="alerts_forest__30e6a7_idx"
            ),
        ),
    ]
