# Generated by Django 5.1.14 on 2026-08-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='角色编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('permissions', models.JSONField(default=list, verbose_name='权限列表')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '系统管理员'), ('operator', '运维人员'), ('forester', '护林员'), ('viewer', '查看者')], default='viewer', max_length=32, verbose_name='角色编码'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='组织名称')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='组织编码')),
                ('org_type', models.CharField(choices=[('group', '集团/指挥中心'), ('bureau', '林业局'), ('station', '管护站'), ('team', '班组'), ('other', '其他')], default='station', max_length=32, verbose_name='组织类型')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='所属区域')),
                ('contact', models.CharField(blank=True, max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='地址')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.organization', verbose_name='上级组织')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'db_table': 'organizations',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.organization', verbose_name='所属组织'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='角色'),
        ),
    ]
