# Generated by Django 5.1.14 on 2026-08-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级角色；本局角色仅本组织子树可见', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.organization', verbose_name='所属组织'),
        ),
    ]
