# Generated by Django 5.1.14 on 2026-08-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_backfill_org_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='林区名称')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='林区编码')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='所属片区/行政区')),
                ('boundary', models.JSONField(blank=True, default=dict, help_text='GeoJSON 或 {center_lng, center_lat, radius_m} 等', verbose_name='边界/范围')),
                ('manager', models.CharField(blank=True, max_length=64, verbose_name='责任人')),
                ('contact', models.CharField(blank=True, max_length=64, verbose_name='联系方式')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forest_zones', to='users.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '林区',
                'verbose_name_plural': '林区',
                'db_table': 'forest_zones',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='forest_zone_organiz_02f162_idx'), models.Index(fields=['organization', 'name'], name='forest_zone_organiz_43e2ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uniq_forest_zone_org_code')],
            },
        ),
    ]
