# Generated by Django 5.1.14 on 2026-08-11 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_backfill_forest_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='为空表示系统内置角色；自建角色挂所属组织，仅本组织子树可见，平级单位互不可见', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.organization', verbose_name='所属组织'),
        ),
        migrations.CreateModel(
            name='DutyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='组名')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='组编码')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('members', models.ManyToManyField(blank=True, related_name='duty_groups', to=settings.AUTH_USER_MODEL, verbose_name='组成员')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_groups', to='users.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '值班组',
                'verbose_name_plural': '值班组',
                'db_table': 'duty_groups',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DutyRosterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_mode', models.CharField(choices=[('three_shift', '三班倒'), ('two_shift', '两班倒'), ('custom', '自定义')], default='three_shift', max_length=32, verbose_name='排班模式')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duty_roster_settings', to='users.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '值班排班配置',
                'verbose_name_plural': '值班排班配置',
                'db_table': 'duty_roster_settings',
            },
        ),
        migrations.CreateModel(
            name='DutyShiftSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='班次编码')),
                ('name', models.CharField(max_length=64, verbose_name='班次名称')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(help_text='可小于开始时间表示跨日', verbose_name='结束时间')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_shifts', to='users.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '值班班次',
                'verbose_name_plural': '值班班次',
                'db_table': 'duty_shift_slots',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(db_index=True, verbose_name='值班日期')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to='users.organization', verbose_name='所属组织')),
                ('users', models.ManyToManyField(blank=True, related_name='duty_assignments', to=settings.AUTH_USER_MODEL, verbose_name='值班人员')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='users.dutygroup', verbose_name='值班组')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.dutyshiftslot', verbose_name='班次')),
            ],
            options={
                'verbose_name': '值班排班',
                'verbose_name_plural': '值班排班',
                'db_table': 'duty_assignments',
                'ordering': ['-duty_date', 'shift__sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='dutygroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_duty_group_org_name'),
        ),
        migrations.AddConstraint(
            model_name='dutyshiftslot',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_duty_shift_org_code'),
        ),
        migrations.AddConstraint(
            model_name='dutyassignment',
            constraint=models.UniqueConstraint(fields=('organization', 'duty_date', 'shift'), name='uniq_duty_assignment_org_date_shift'),
        ),
    ]
