# Generated by Django 5.1.14 on 2026-08-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_forest_zone_regions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True, verbose_name="单例键"
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        default="林智森林智能监控平台",
                        max_length=128,
                        verbose_name="系统平台名称",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "平台设置",
                "verbose_name_plural": "平台设置",
                "db_table": "platform_settings",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refresh_interval",
                    models.CharField(
                        default="10秒", max_length=32, verbose_name="数据刷新间隔"
                    ),
                ),
                (
                    "default_map_layer",
                    models.CharField(
                        default="标准地图", max_length=64, verbose_name="默认地图图层"
                    ),
                ),
                (
                    "coordinate_system",
                    models.CharField(
                        default="WGS-84", max_length=32, verbose_name="坐标系"
                    ),
                ),
                (
                    "video_capture",
                    models.CharField(
                        default="连续采集", max_length=64, verbose_name="视频采集模式"
                    ),
                ),
                (
                    "sensor_interval",
                    models.CharField(
                        default="5分钟", max_length=32, verbose_name="传感上报间隔"
                    ),
                ),
                (
                    "video_codec",
                    models.CharField(
                        default="H.265 (自适应)", max_length=64, verbose_name="视频编码"
                    ),
                ),
                (
                    "offline_cache_days",
                    models.CharField(
                        default="≥7天", max_length=32, verbose_name="离线缓存"
                    ),
                ),
                (
                    "resume_upload",
                    models.BooleanField(default=True, verbose_name="断点续传"),
                ),
                (
                    "notify_in_app",
                    models.BooleanField(default=True, verbose_name="站内通知"),
                ),
                (
                    "notify_app_push",
                    models.BooleanField(default=True, verbose_name="App 推送"),
                ),
                (
                    "notify_sms",
                    models.BooleanField(default=True, verbose_name="短信通知"),
                ),
                (
                    "notify_voice_call",
                    models.BooleanField(default=True, verbose_name="语音呼叫"),
                ),
                (
                    "notify_forestry_line",
                    models.BooleanField(default=True, verbose_name="林业专线"),
                ),
                (
                    "duty_mode_label",
                    models.CharField(
                        default="三班倒", max_length=64, verbose_name="值班模式展示"
                    ),
                ),
                (
                    "data_retention",
                    models.CharField(
                        default="90天", max_length=64, verbose_name="数据保留"
                    ),
                ),
                (
                    "video_storage",
                    models.CharField(
                        default="告警片段保留30天",
                        max_length=128,
                        verbose_name="视频存储策略",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_settings",
                        to="users.organization",
                        verbose_name="所属组织",
                    ),
                ),
            ],
            options={
                "verbose_name": "组织系统设置",
                "verbose_name_plural": "组织系统设置",
                "db_table": "organization_settings",
            },
        ),
    ]
