# Generated by Django 5.1.14 on 2026-09-17 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_system_settings_org_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        db_index=True,
                        help_text="第三方 JWT 的 iss 声明值，如 provincial_emergency",
                        max_length=64,
                        verbose_name="签发方",
                    ),
                ),
                (
                    "sub",
                    models.CharField(
                        db_index=True,
                        help_text="第三方 JWT 的 sub 声明值",
                        max_length=128,
                        verbose_name="外部主体标识",
                    ),
                ),
                (
                    "claims",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="最近一次 claims 快照"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近 SSO 登录时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "第三方身份",
                "verbose_name_plural": "第三方身份",
                "db_table": "external_identities",
                "indexes": [
                    models.Index(
                        fields=["issuer", "sub"], name="external_id_issuer_2d49b7_idx"
                    )
                ],
                "unique_together": {("issuer", "sub")},
            },
        ),
    ]
