# Generated by Django 5.1.14 on 2026-08-06 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='设备ID')),
                ('device_name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('dual_camera', '双目智能监测云台'), ('env_sensor', '多参数环境传感器'), ('ai_gateway', 'AI边缘网关'), ('drone', '无人机')], max_length=32, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('alarm', '告警'), ('maintenance', '维护中')], default='offline', max_length=32, verbose_name='设备状态')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='海拔')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='所属区域')),
                ('forest_zone', models.CharField(blank=True, max_length=128, verbose_name='林区')),
                ('firmware_version', models.CharField(blank=True, max_length=32, verbose_name='固件版本')),
                ('hardware_version', models.CharField(blank=True, max_length=32, verbose_name='硬件版本')),
                ('manufacturer', models.CharField(blank=True, max_length=128, verbose_name='厂商')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='最后维护日期')),
                ('communication_type', models.CharField(choices=[('4g', '4G'), ('lora', 'LoRa'), ('wifi', 'WiFi'), ('ethernet', '有线')], default='4g', max_length=32, verbose_name='通信方式')),
                ('signal_strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='信号强度')),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='电池电量')),
                ('pan_angle', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='水平角度')),
                ('tilt_angle', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='垂直角度')),
                ('last_online_time', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_type', 'status'], name='devices_device__ed67e0_idx'), models.Index(fields=['region', 'forest_zone'], name='devices_region_49cfad_idx'), models.Index(fields=['last_online_time'], name='devices_last_on_887dd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=64, verbose_name='指令类型')),
                ('command_params', models.JSONField(default=dict, verbose_name='指令参数')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('delivered', '已送达'), ('executed', '已执行'), ('failed', '失败'), ('timeout', '超时')], default='pending', max_length=32, verbose_name='指令状态')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
            ],
            options={
                'verbose_name': '设备指令',
                'verbose_name_plural': '设备指令',
                'db_table': 'device_commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='采集时间')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='风速')),
                ('wind_direction', models.IntegerField(blank=True, null=True, verbose_name='风向')),
                ('light_intensity', models.FloatField(blank=True, null=True, verbose_name='光照强度')),
                ('soil_moisture_10cm', models.FloatField(blank=True, null=True, verbose_name='10cm土壤湿度')),
                ('soil_moisture_30cm', models.FloatField(blank=True, null=True, verbose_name='30cm土壤湿度')),
                ('soil_moisture_60cm', models.FloatField(blank=True, null=True, verbose_name='60cm土壤湿度')),
                ('fuel_moisture', models.FloatField(blank=True, null=True, verbose_name='可燃物含水率')),
                ('video_status', models.CharField(blank=True, choices=[('normal', '正常'), ('blurry', '模糊'), ('obstructed', '遮挡'), ('no_signal', '无信号')], max_length=32, null=True, verbose_name='视频状态')),
                ('thermal_max_temp', models.FloatField(blank=True, null=True, verbose_name='最高温度')),
                ('thermal_min_temp', models.FloatField(blank=True, null=True, verbose_name='最低温度')),
                ('thermal_avg_temp', models.FloatField(blank=True, null=True, verbose_name='平均温度')),
                ('thermal_hotspot_x', models.IntegerField(blank=True, null=True, verbose_name='热源X坐标')),
                ('thermal_hotspot_y', models.IntegerField(blank=True, null=True, verbose_name='热源Y坐标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device')),
            ],
            options={
                'verbose_name': '设备遥测数据',
                'verbose_name_plural': '设备遥测数据',
                'db_table': 'device_telemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='device_tele_device__08feaa_idx'), models.Index(fields=['-timestamp'], name='device_tele_timesta_8eb493_idx')],
            },
        ),
    ]
