# Generated by Django 5.1.14 on 2026-08-10 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='预置位号')),
                ('name', models.CharField(max_length=128, verbose_name='预置位名称')),
                ('pan_angle', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='水平角度')),
                ('tilt_angle', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='垂直角度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '云台预置位',
                'verbose_name_plural': '云台预置位',
                'db_table': 'device_presets',
                'ordering': ['preset_id'],
            },
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='关联ID'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', '-created_at'], name='device_comm_device__b06793_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['command_type', '-created_at'], name='device_comm_command_102c78_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['status', '-created_at'], name='device_comm_status_6b643c_idx'),
        ),
        migrations.AddField(
            model_name='devicepreset',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='devices.device'),
        ),
        migrations.AlterUniqueTogether(
            name='devicepreset',
            unique_together={('device', 'preset_id')},
        ),
    ]
