# Generated by Django 5.1.14 on 2026-08-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_org_tenant_scope'),
        ('users', '0006_forest_zone_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='forest_zone_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='users.forestzone', verbose_name='所属林区'),
        ),
        migrations.AlterField(
            model_name='device',
            name='forest_zone',
            field=models.CharField(blank=True, max_length=128, verbose_name='林区(冗余名)'),
        ),
    ]
