# Generated by Django 5.1.14 on 2026-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_forest_zone_master"),
        ("users", "0010_system_settings_org_scope"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["organization", "forest_zone", "status"],
                name="devices_organiz_3cda1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["organization", "region", "status"],
                name="devices_organiz_26c799_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["forest_zone_ref", "status"], name="devices_forest__f9672a_idx"
            ),
        ),
    ]
