# Generated by Django 5.1.14 on 2026-08-06 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True, verbose_name='报告日期')),
                ('total_devices', models.IntegerField(default=0, verbose_name='设备总数')),
                ('online_devices', models.IntegerField(default=0, verbose_name='在线设备')),
                ('online_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='在线率')),
                ('total_alerts', models.IntegerField(default=0, verbose_name='告警总数')),
                ('resolved_alerts', models.IntegerField(default=0, verbose_name='已处置告警')),
                ('resolution_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='处置率')),
                ('avg_response_time', models.IntegerField(default=0, verbose_name='平均响应时间(秒)')),
                ('false_alarm_count', models.IntegerField(default=0, verbose_name='误报数量')),
                ('false_alarm_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='误报率')),
                ('avg_temperature', models.FloatField(blank=True, null=True, verbose_name='平均温度')),
                ('max_temperature', models.FloatField(blank=True, null=True, verbose_name='最高温度')),
                ('avg_humidity', models.FloatField(blank=True, null=True, verbose_name='平均湿度')),
                ('avg_wind_speed', models.FloatField(blank=True, null=True, verbose_name='平均风速')),
                ('carbon_sequestration', models.FloatField(default=0, verbose_name='碳汇值(吨)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '日报',
                'verbose_name_plural': '日报',
                'db_table': 'daily_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=128, verbose_name='区域')),
                ('stat_date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('stat_hour', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='统计小时')),
                ('avg_temperature', models.FloatField(blank=True, null=True, verbose_name='平均温度')),
                ('max_temperature', models.FloatField(blank=True, null=True, verbose_name='最高温度')),
                ('min_temperature', models.FloatField(blank=True, null=True, verbose_name='最低温度')),
                ('avg_humidity', models.FloatField(blank=True, null=True, verbose_name='平均湿度')),
                ('max_humidity', models.FloatField(blank=True, null=True, verbose_name='最高湿度')),
                ('min_humidity', models.FloatField(blank=True, null=True, verbose_name='最低湿度')),
                ('avg_wind_speed', models.FloatField(blank=True, null=True, verbose_name='平均风速')),
                ('max_wind_speed', models.FloatField(blank=True, null=True, verbose_name='最大风速')),
                ('avg_light_intensity', models.FloatField(blank=True, null=True, verbose_name='平均光照强度')),
                ('avg_soil_moisture', models.FloatField(blank=True, null=True, verbose_name='平均土壤湿度')),
                ('avg_fuel_moisture', models.FloatField(blank=True, null=True, verbose_name='平均可燃物含水率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '环境数据汇总',
                'verbose_name_plural': '环境数据汇总',
                'db_table': 'environmental_data',
                'ordering': ['-stat_date', '-stat_hour'],
                'unique_together': {('region', 'stat_date', 'stat_hour')},
            },
        ),
        migrations.CreateModel(
            name='DeviceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('uptime_hours', models.FloatField(default=0, verbose_name='在线时长(小时)')),
                ('availability_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='可用率')),
                ('alert_count', models.IntegerField(default=0, verbose_name='告警次数')),
                ('fault_count', models.IntegerField(default=0, verbose_name='故障次数')),
                ('data_completeness', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='数据完整率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='devices.device')),
            ],
            options={
                'verbose_name': '设备统计',
                'verbose_name_plural': '设备统计',
                'db_table': 'device_statistics',
                'ordering': ['-stat_date'],
                'unique_together': {('device', 'stat_date')},
            },
        ),
    ]
