# Generated by Django 5.1.14 on 2026-08-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0004_org_tenant_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='users.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='report_date',
            field=models.DateField(db_index=True, verbose_name='报告日期'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('organization', 'report_date')},
        ),
    ]
